---
version: "2.1"
services:
  davos:
    image: lscr.io/linuxserver/davos:latest
    container_name: davos
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/drok/docker/davos/config:/config
      - /home/drok/docker/davos/download:/download
    ports:
      - 8083:8080
    restart: unless-stopped
