version: "3.7"

services:
  node-red:
    image: nodered/node-red:latest
    environment:
      - TZ=America/New_York
      - NODE_RED_CREDENTIAL_SECRET=drokDROK63
    ports:
      - "1880:1880"
    networks:
      - node-red-net
    volumes:
      - node-red-data:/data

volumes:
  node-red-data:

networks:
  node-red-net:    
