version: '3.1'

services:

  ghost:
    image: ghost:latest
    restart: always
    ports:
      - 3001:2368
    environment:
      # see https://ghost.org/docs/config/#configuration-options
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: password
      database__connection__database: ghost
      # this url value is just an example, and is likely wrong for your environment!
      url: https://drokdev.pro
      # contrary to the default mentioned in the linked documentation, this image defaults to NODE_ENV=production (so development mode needs to be explicitly specified if desired)
      #NODE_ENV: development
      #privileged: true
      #links: 
      #- db
    volumes:
      #- /DATA/AppData/ghost:/var/lib/ghost/content
        - ghost:/var/lib/ghost/content
  db:
    image: mysql/mysql-server:latest
    restart: always
      #ports:
      #- "3306:3306"
    environment:
      #MYSQL_DATABASE: ghost
      #MYSQL_USER: user
      #MYSQL_USER: password 
      MYSQL_ROOT_PASSWORD: password
    volumes:
        #- /DATA/AppData/ghost-mysql:/var/lib/mysql
        - db:/var/lib/mysql
volumes:
   ghost: {}
   db: {}
