---
version: "2.1"
services:
  wikijs:
    image: lscr.io/linuxserver/wikijs:latest
    container_name: wikijs
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /DATA/AppData/wikijs/config:/config
      - /DATA/AppData/wikijs/data:/data
    ports:
      - 3000:3000
    restart: unless-stopped
